sonar.projectKey=FCM-Tech
sonar.host.url=http://localhost:9000
sonar.sources=cypress
sonar.inclusions=**/*.js
sonar.exclusions=**/*.spec.js,**/node_modules/**
sonar.login=sqp_37d2992888ed36b892337ab2d1ad2cae3d1a077f
sonar.javascript.lcov.reportPaths=coverage/lcov.info