name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Run Cypress tests
        run: yarn cypress:run
        
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Additional arguments to the sonarcloud scanner
          args: >
            -Dsonar.projectKey=MMarioB_qa-tech-challenge
            -Dsonar.organization=mmariob
            -Dsonar.sources=.
            -Dsonar.tests=cypress
            -Dsonar.test.inclusions=**/*.spec.js,**/*.cy.js,**/*.feature
            -Dsonar.exclusions=node_modules/**,cypress/videos/**,cypress/screenshots/**,cypress/downloads/**,**/*.spec.js,**/*.cy.js,**/*.feature
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sourceEncoding=UTF-8